name: Bankole Salako
description: Software and every other good stuff
meta_description: "Bankole Salako; software and every other good stuff"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
#baseurl: /
domain_name: 'http://bxnkole.github.io'
google_analytics: 'UA-98298067-1'
disqus: true
disqus_shortname: 'http-bxnkole-github-io'

# Details for the RSS feed generator
url:            'https://bxnkole.github.io'
author:         'Bankole Salako'
authorTwitter:  'bxnkole'
logo:           '/assets/images/my-avatar.png'

permalink:       /:year/:title/

avatar:          'my-avatar.png'

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

gems:
    - jekyll-seo-tag
    - jekyll-paginate

twitter:
    username: bxnkole

social:
  name: Bankole Salako
  links:
    - https://twitter.com/bxnkole
    - https://www.facebook.com/bankole.salako
    - https://www.linkedin.com/in/bankolesalako
    - https://github.com/bxnkole